ci:
  autoupdate_schedule: quarterly
exclude: '^tests/examples/.*\.html$'
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
     - id: pyupgrade
       args: [--py37-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
     - id: check-added-large-files
     - id: check-ast
     - id: check-json
     - id: check-merge-conflict
     - id: check-toml
     - id: check-yaml
     - id: debug-statements
     - id: detect-private-key
     - id: fix-byte-order-marker
     - id: fix-encoding-pragma
       args: [--remove]
     - id: trailing-whitespace
       args: [--markdown-linebreak-ext=md]
       exclude: ^tests/examples/pacer/nef/s3/.*\.txt$

  - repo: https://github.com/ikamensh/flynt/
    rev: '1.0.1'
    hooks:
     - id: flynt
       args: [--line-length=79, --transform-concats]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
     - id: black
       additional_dependencies: ['click==8.0.4']

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
     - id: isort
       name: isort (python)
